services:
  tap2test-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tap2test-api
    ports:
      - "8050:8050"
      - "8051:8051"
    volumes:
      - /etc/ssl/certs/tap2test:/cert
      - ./Videos:/app/Videos/
      - ./Images:/app/Images/
    env_file: .env
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: "http://0.0.0.0:8050;https://0.0.0.0:8051"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/cert/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${CERT_PW}"
    restart: unless-stopped
